name: ReleaseProd
on:
  push:
    branches:
      - 'prod'
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
      - name: Check for safe merge
        run: |
          git config --global user.name 'bobgobills'
          git config --global user.email 'bobgobills@users.noreply.github.com'
          ./bin/merge-check.sh
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn semantic-release
      - name: Main
        run: |
          git config --global user.name 'bobgobills'
          git config --global user.email 'bobgobills@users.noreply.github.com'
          git checkout main
          git merge --no-ff prod
          git push origin main

